### ISSUE TITLE
getTimes fails to calculate sunrise during summer

### ISSUE THREAD

**Issue by jhsware** [shanus/flutter_suncalc#1]
This works:
```dart
  test('getTimes returns sun phases in summer', () {
    var lat = 50.5;
    var lng = 30.5;
    var date = new DateTime.utc(2020, 5, 27);
    var times = SunCalc.getTimes(date, lat, lng);
    expect(times["sunrise"], isA<DateTime>());
  });
```

This fails but should return close to {"sunrise": 04:47, "sunset": 21:08}:

```dart
  test('getTimes returns sun phases in summer', () {
    var lat = 50.5;
    var lng = 30.5;
    var date = new DateTime.utc(2020, 6, 10);
    var times = SunCalc.getTimes(date, lat, lng);
    expect(times["sunrise"], isA<DateTime>());
  });
```

**Comment by acrovato** [comment]
I also noticed that `getTimes` might fail for some combinations of locations and times. This occurs because `getTimes` will attempt to compute all the ephemeris, and some are invalid.  
For example, you cannot get the "sunrise" in June for a location in North-West Europe. In that case,  "night" and "nightEnd" will be ill-defined, if I remember correctly.

Since `getTimes` does not allow the user to chose only valid ephemeris, I think the method should have the responsibility of always returning a valid `Map<String,DateTime>`.  
I suggest this kind of change (lib/flutter_suncalc.dart::20):
```dart
DateTime fromJulian(num j) {
  if (j.isNan)
     return null;
  else
     return julianEpoch.add(Duration(milliseconds: (j * Duration.millisecondsPerDay).floor()));
}
```

Additional notes:
1) the problem happens because the argument of an arc cosine (line 112) is out of bound. Since there are several arc functions, it would be good to add some tests to prevent such a similar behavior to happen.
2) related issue is original code: https://github.com/mourner/suncalc/issues/134

**Comment by computerlyrik** [comment]
Had this problem, now using 
```pubspec.yml
  flutter_suncalc:
    git:
      url: https://github.com/jhsware/flutter_suncalc.git
```
as a workaround.
